name: Vercel Preview Deployment
env:
  "orgId": "GRA2rccHPMHVTlTdoQQ0Toa8"
  "projectId": "prj_UKiZPOJGjQ9y202JRLe0XOIAeLIX"
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token='3Giqs5xxU0COyo6l85A8oDJr'
      - name: Build Project Artifacts
        run: vercel build --token='3Giqs5xxU0COyo6l85A8oDJr'
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token='3Giqs5xxU0COyo6l85A8oDJr'
